/**
 * generated by Xtext
 */
package xtext.validation;

import xtext.validation.AbstractQueryITValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class QueryITValidator extends AbstractQueryITValidator {
}
