/**
 * generated by Xtext
 */
package xtext.serializer;

import xtext.serializer.AbstractQueryITSyntacticSequencer;

@SuppressWarnings("all")
public class QueryITSyntacticSequencer extends AbstractQueryITSyntacticSequencer {
}
