/**
 * generated by Xtext
 */
package xtext.serializer;

import xtext.serializer.AbstractQueryITSemanticSequencer;

@SuppressWarnings("all")
public class QueryITSemanticSequencer extends AbstractQueryITSemanticSequencer {
}
