/*
* generated by Xtext
*/
package xtext.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class QueryITGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class SurveyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Survey");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final UnorderedGroup cUnorderedGroup_0 = (UnorderedGroup)cGroup.eContents().get(0);
		private final Assignment cHideNavigationButtonsAssignment_0_0 = (Assignment)cUnorderedGroup_0.eContents().get(0);
		private final Keyword cHideNavigationButtonsHideNavigationButtonsKeyword_0_0_0 = (Keyword)cHideNavigationButtonsAssignment_0_0.eContents().get(0);
		private final Assignment cHidePageTitlesAssignment_0_1 = (Assignment)cUnorderedGroup_0.eContents().get(1);
		private final Keyword cHidePageTitlesHidePageTitlesKeyword_0_1_0 = (Keyword)cHidePageTitlesAssignment_0_1.eContents().get(0);
		private final Assignment cHideQuestionNumbersAssignment_0_2 = (Assignment)cUnorderedGroup_0.eContents().get(2);
		private final Keyword cHideQuestionNumbersHideQuestionNumbersKeyword_0_2_0 = (Keyword)cHideQuestionNumbersAssignment_0_2.eContents().get(0);
		private final Assignment cHidePageNumbersAssignment_0_3 = (Assignment)cUnorderedGroup_0.eContents().get(3);
		private final Keyword cHidePageNumbersHidePageNumbersKeyword_0_3_0 = (Keyword)cHidePageNumbersAssignment_0_3.eContents().get(0);
		private final Group cGroup_0_4 = (Group)cUnorderedGroup_0.eContents().get(4);
		private final Keyword cAuthorSKeyword_0_4_0 = (Keyword)cGroup_0_4.eContents().get(0);
		private final Assignment cAuthorAssignment_0_4_1 = (Assignment)cGroup_0_4.eContents().get(1);
		private final RuleCall cAuthorEStringParserRuleCall_0_4_1_0 = (RuleCall)cAuthorAssignment_0_4_1.eContents().get(0);
		private final Group cGroup_0_4_2 = (Group)cGroup_0_4.eContents().get(2);
		private final Keyword cCommaKeyword_0_4_2_0 = (Keyword)cGroup_0_4_2.eContents().get(0);
		private final Assignment cAuthorAssignment_0_4_2_1 = (Assignment)cGroup_0_4_2.eContents().get(1);
		private final RuleCall cAuthorEStringParserRuleCall_0_4_2_1_0 = (RuleCall)cAuthorAssignment_0_4_2_1.eContents().get(0);
		private final Group cGroup_0_5 = (Group)cUnorderedGroup_0.eContents().get(5);
		private final Keyword cTitleKeyword_0_5_0 = (Keyword)cGroup_0_5.eContents().get(0);
		private final Assignment cTitleAssignment_0_5_1 = (Assignment)cGroup_0_5.eContents().get(1);
		private final RuleCall cTitleEStringParserRuleCall_0_5_1_0 = (RuleCall)cTitleAssignment_0_5_1.eContents().get(0);
		private final Group cGroup_0_6 = (Group)cUnorderedGroup_0.eContents().get(6);
		private final Keyword cTimeLimitKeyword_0_6_0 = (Keyword)cGroup_0_6.eContents().get(0);
		private final Assignment cTimeLimitAssignment_0_6_1 = (Assignment)cGroup_0_6.eContents().get(1);
		private final RuleCall cTimeLimitEIntParserRuleCall_0_6_1_0 = (RuleCall)cTimeLimitAssignment_0_6_1.eContents().get(0);
		private final Group cGroup_0_7 = (Group)cUnorderedGroup_0.eContents().get(7);
		private final Keyword cCompletedMessageKeyword_0_7_0 = (Keyword)cGroup_0_7.eContents().get(0);
		private final Assignment cCompletedMessageAssignment_0_7_1 = (Assignment)cGroup_0_7.eContents().get(1);
		private final RuleCall cCompletedMessageEStringParserRuleCall_0_7_1_0 = (RuleCall)cCompletedMessageAssignment_0_7_1.eContents().get(0);
		private final Group cGroup_0_8 = (Group)cUnorderedGroup_0.eContents().get(8);
		private final Keyword cButtonNextTextKeyword_0_8_0 = (Keyword)cGroup_0_8.eContents().get(0);
		private final Assignment cPageNextTextAssignment_0_8_1 = (Assignment)cGroup_0_8.eContents().get(1);
		private final RuleCall cPageNextTextEStringParserRuleCall_0_8_1_0 = (RuleCall)cPageNextTextAssignment_0_8_1.eContents().get(0);
		private final Group cGroup_0_9 = (Group)cUnorderedGroup_0.eContents().get(9);
		private final Keyword cButtonPrevTextKeyword_0_9_0 = (Keyword)cGroup_0_9.eContents().get(0);
		private final Assignment cPagePrevTextAssignment_0_9_1 = (Assignment)cGroup_0_9.eContents().get(1);
		private final RuleCall cPagePrevTextEStringParserRuleCall_0_9_1_0 = (RuleCall)cPagePrevTextAssignment_0_9_1.eContents().get(0);
		private final Group cGroup_0_10 = (Group)cUnorderedGroup_0.eContents().get(10);
		private final Keyword cButtonCompletedTextKeyword_0_10_0 = (Keyword)cGroup_0_10.eContents().get(0);
		private final Assignment cCompleteTextAssignment_0_10_1 = (Assignment)cGroup_0_10.eContents().get(1);
		private final RuleCall cCompleteTextEStringParserRuleCall_0_10_1_0 = (RuleCall)cCompleteTextAssignment_0_10_1.eContents().get(0);
		private final Group cGroup_0_11 = (Group)cUnorderedGroup_0.eContents().get(11);
		private final Keyword cQuestionTitleLocationKeyword_0_11_0 = (Keyword)cGroup_0_11.eContents().get(0);
		private final Assignment cQuestionTitleLocationAssignment_0_11_1 = (Assignment)cGroup_0_11.eContents().get(1);
		private final RuleCall cQuestionTitleLocationTitleLocationEnumRuleCall_0_11_1_0 = (RuleCall)cQuestionTitleLocationAssignment_0_11_1.eContents().get(0);
		private final Group cGroup_0_12 = (Group)cUnorderedGroup_0.eContents().get(12);
		private final Keyword cProgressBarLocationKeyword_0_12_0 = (Keyword)cGroup_0_12.eContents().get(0);
		private final Assignment cShowProgressBarAssignment_0_12_1 = (Assignment)cGroup_0_12.eContents().get(1);
		private final RuleCall cShowProgressBarProgressBarLocationEnumRuleCall_0_12_1_0 = (RuleCall)cShowProgressBarAssignment_0_12_1.eContents().get(0);
		private final Assignment cPagesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPagesPageParserRuleCall_1_0 = (RuleCall)cPagesAssignment_1.eContents().get(0);
		private final Assignment cPagesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cPagesPageParserRuleCall_2_0 = (RuleCall)cPagesAssignment_2.eContents().get(0);
		
		//Survey:
		//	(hideNavigationButtons?="hideNavigationButtons"? & hidePageTitles?="hidePageTitles"? &
		//	hideQuestionNumbers?="hideQuestionNumbers"? & hidePageNumbers?="hidePageNumbers"? & ("author(s):" author+=EString
		//	("," author+=EString)*)? & ("title:" title=EString)? & ("timeLimit:" timeLimit=EInt)? & ("completedMessage:"
		//	completedMessage=EString)? & ("buttonNextText:" pageNextText=EString)? & ("buttonPrevText:" pagePrevText=EString)? &
		//	("buttonCompletedText:" completeText=EString)? & ("questionTitleLocation:" questionTitleLocation=TitleLocation)? &
		//	("progressBarLocation:" showProgressBar=ProgressBarLocation)?) pages+=Page pages+=Page*;
		public ParserRule getRule() { return rule; }

		//(hideNavigationButtons?="hideNavigationButtons"? & hidePageTitles?="hidePageTitles"? &
		//hideQuestionNumbers?="hideQuestionNumbers"? & hidePageNumbers?="hidePageNumbers"? & ("author(s):" author+=EString (","
		//author+=EString)*)? & ("title:" title=EString)? & ("timeLimit:" timeLimit=EInt)? & ("completedMessage:"
		//completedMessage=EString)? & ("buttonNextText:" pageNextText=EString)? & ("buttonPrevText:" pagePrevText=EString)? &
		//("buttonCompletedText:" completeText=EString)? & ("questionTitleLocation:" questionTitleLocation=TitleLocation)? &
		//("progressBarLocation:" showProgressBar=ProgressBarLocation)?) pages+=Page pages+=Page*
		public Group getGroup() { return cGroup; }

		//hideNavigationButtons?="hideNavigationButtons"? & hidePageTitles?="hidePageTitles"? &
		//hideQuestionNumbers?="hideQuestionNumbers"? & hidePageNumbers?="hidePageNumbers"? & ("author(s):" author+=EString (","
		//author+=EString)*)? & ("title:" title=EString)? & ("timeLimit:" timeLimit=EInt)? & ("completedMessage:"
		//completedMessage=EString)? & ("buttonNextText:" pageNextText=EString)? & ("buttonPrevText:" pagePrevText=EString)? &
		//("buttonCompletedText:" completeText=EString)? & ("questionTitleLocation:" questionTitleLocation=TitleLocation)? &
		//("progressBarLocation:" showProgressBar=ProgressBarLocation)?
		public UnorderedGroup getUnorderedGroup_0() { return cUnorderedGroup_0; }

		//hideNavigationButtons?="hideNavigationButtons"?
		public Assignment getHideNavigationButtonsAssignment_0_0() { return cHideNavigationButtonsAssignment_0_0; }

		//"hideNavigationButtons"
		public Keyword getHideNavigationButtonsHideNavigationButtonsKeyword_0_0_0() { return cHideNavigationButtonsHideNavigationButtonsKeyword_0_0_0; }

		//hidePageTitles?="hidePageTitles"?
		public Assignment getHidePageTitlesAssignment_0_1() { return cHidePageTitlesAssignment_0_1; }

		//"hidePageTitles"
		public Keyword getHidePageTitlesHidePageTitlesKeyword_0_1_0() { return cHidePageTitlesHidePageTitlesKeyword_0_1_0; }

		//hideQuestionNumbers?="hideQuestionNumbers"?
		public Assignment getHideQuestionNumbersAssignment_0_2() { return cHideQuestionNumbersAssignment_0_2; }

		//"hideQuestionNumbers"
		public Keyword getHideQuestionNumbersHideQuestionNumbersKeyword_0_2_0() { return cHideQuestionNumbersHideQuestionNumbersKeyword_0_2_0; }

		//hidePageNumbers?="hidePageNumbers"?
		public Assignment getHidePageNumbersAssignment_0_3() { return cHidePageNumbersAssignment_0_3; }

		//"hidePageNumbers"
		public Keyword getHidePageNumbersHidePageNumbersKeyword_0_3_0() { return cHidePageNumbersHidePageNumbersKeyword_0_3_0; }

		//("author(s):" author+=EString ("," author+=EString)*)?
		public Group getGroup_0_4() { return cGroup_0_4; }

		//"author(s):"
		public Keyword getAuthorSKeyword_0_4_0() { return cAuthorSKeyword_0_4_0; }

		//author+=EString
		public Assignment getAuthorAssignment_0_4_1() { return cAuthorAssignment_0_4_1; }

		//EString
		public RuleCall getAuthorEStringParserRuleCall_0_4_1_0() { return cAuthorEStringParserRuleCall_0_4_1_0; }

		//("," author+=EString)*
		public Group getGroup_0_4_2() { return cGroup_0_4_2; }

		//","
		public Keyword getCommaKeyword_0_4_2_0() { return cCommaKeyword_0_4_2_0; }

		//author+=EString
		public Assignment getAuthorAssignment_0_4_2_1() { return cAuthorAssignment_0_4_2_1; }

		//EString
		public RuleCall getAuthorEStringParserRuleCall_0_4_2_1_0() { return cAuthorEStringParserRuleCall_0_4_2_1_0; }

		//("title:" title=EString)?
		public Group getGroup_0_5() { return cGroup_0_5; }

		//"title:"
		public Keyword getTitleKeyword_0_5_0() { return cTitleKeyword_0_5_0; }

		//title=EString
		public Assignment getTitleAssignment_0_5_1() { return cTitleAssignment_0_5_1; }

		//EString
		public RuleCall getTitleEStringParserRuleCall_0_5_1_0() { return cTitleEStringParserRuleCall_0_5_1_0; }

		//("timeLimit:" timeLimit=EInt)?
		public Group getGroup_0_6() { return cGroup_0_6; }

		//"timeLimit:"
		public Keyword getTimeLimitKeyword_0_6_0() { return cTimeLimitKeyword_0_6_0; }

		//timeLimit=EInt
		public Assignment getTimeLimitAssignment_0_6_1() { return cTimeLimitAssignment_0_6_1; }

		//EInt
		public RuleCall getTimeLimitEIntParserRuleCall_0_6_1_0() { return cTimeLimitEIntParserRuleCall_0_6_1_0; }

		//("completedMessage:" completedMessage=EString)?
		public Group getGroup_0_7() { return cGroup_0_7; }

		//"completedMessage:"
		public Keyword getCompletedMessageKeyword_0_7_0() { return cCompletedMessageKeyword_0_7_0; }

		//completedMessage=EString
		public Assignment getCompletedMessageAssignment_0_7_1() { return cCompletedMessageAssignment_0_7_1; }

		//EString
		public RuleCall getCompletedMessageEStringParserRuleCall_0_7_1_0() { return cCompletedMessageEStringParserRuleCall_0_7_1_0; }

		//("buttonNextText:" pageNextText=EString)?
		public Group getGroup_0_8() { return cGroup_0_8; }

		//"buttonNextText:"
		public Keyword getButtonNextTextKeyword_0_8_0() { return cButtonNextTextKeyword_0_8_0; }

		//pageNextText=EString
		public Assignment getPageNextTextAssignment_0_8_1() { return cPageNextTextAssignment_0_8_1; }

		//EString
		public RuleCall getPageNextTextEStringParserRuleCall_0_8_1_0() { return cPageNextTextEStringParserRuleCall_0_8_1_0; }

		//("buttonPrevText:" pagePrevText=EString)?
		public Group getGroup_0_9() { return cGroup_0_9; }

		//"buttonPrevText:"
		public Keyword getButtonPrevTextKeyword_0_9_0() { return cButtonPrevTextKeyword_0_9_0; }

		//pagePrevText=EString
		public Assignment getPagePrevTextAssignment_0_9_1() { return cPagePrevTextAssignment_0_9_1; }

		//EString
		public RuleCall getPagePrevTextEStringParserRuleCall_0_9_1_0() { return cPagePrevTextEStringParserRuleCall_0_9_1_0; }

		//("buttonCompletedText:" completeText=EString)?
		public Group getGroup_0_10() { return cGroup_0_10; }

		//"buttonCompletedText:"
		public Keyword getButtonCompletedTextKeyword_0_10_0() { return cButtonCompletedTextKeyword_0_10_0; }

		//completeText=EString
		public Assignment getCompleteTextAssignment_0_10_1() { return cCompleteTextAssignment_0_10_1; }

		//EString
		public RuleCall getCompleteTextEStringParserRuleCall_0_10_1_0() { return cCompleteTextEStringParserRuleCall_0_10_1_0; }

		//("questionTitleLocation:" questionTitleLocation=TitleLocation)?
		public Group getGroup_0_11() { return cGroup_0_11; }

		//"questionTitleLocation:"
		public Keyword getQuestionTitleLocationKeyword_0_11_0() { return cQuestionTitleLocationKeyword_0_11_0; }

		//questionTitleLocation=TitleLocation
		public Assignment getQuestionTitleLocationAssignment_0_11_1() { return cQuestionTitleLocationAssignment_0_11_1; }

		//TitleLocation
		public RuleCall getQuestionTitleLocationTitleLocationEnumRuleCall_0_11_1_0() { return cQuestionTitleLocationTitleLocationEnumRuleCall_0_11_1_0; }

		//("progressBarLocation:" showProgressBar=ProgressBarLocation)?
		public Group getGroup_0_12() { return cGroup_0_12; }

		//"progressBarLocation:"
		public Keyword getProgressBarLocationKeyword_0_12_0() { return cProgressBarLocationKeyword_0_12_0; }

		//showProgressBar=ProgressBarLocation
		public Assignment getShowProgressBarAssignment_0_12_1() { return cShowProgressBarAssignment_0_12_1; }

		//ProgressBarLocation
		public RuleCall getShowProgressBarProgressBarLocationEnumRuleCall_0_12_1_0() { return cShowProgressBarProgressBarLocationEnumRuleCall_0_12_1_0; }

		//pages+=Page
		public Assignment getPagesAssignment_1() { return cPagesAssignment_1; }

		//Page
		public RuleCall getPagesPageParserRuleCall_1_0() { return cPagesPageParserRuleCall_1_0; }

		//pages+=Page*
		public Assignment getPagesAssignment_2() { return cPagesAssignment_2; }

		//Page
		public RuleCall getPagesPageParserRuleCall_2_0() { return cPagesPageParserRuleCall_2_0; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class PageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Page");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1 = (UnorderedGroup)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cUnorderedGroup_1.eContents().get(0);
		private final Keyword cTitleKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Assignment cTitleAssignment_1_0_1 = (Assignment)cGroup_1_0.eContents().get(1);
		private final RuleCall cTitleEStringParserRuleCall_1_0_1_0 = (RuleCall)cTitleAssignment_1_0_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cUnorderedGroup_1.eContents().get(1);
		private final Keyword cVisibleIfKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Assignment cVisibleIfAssignment_1_1_1 = (Assignment)cGroup_1_1.eContents().get(1);
		private final RuleCall cVisibleIfEStringParserRuleCall_1_1_1_0 = (RuleCall)cVisibleIfAssignment_1_1_1.eContents().get(0);
		private final Assignment cQuestionsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cQuestionsQuestionParserRuleCall_2_0 = (RuleCall)cQuestionsAssignment_2.eContents().get(0);
		private final Assignment cQuestionsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cQuestionsQuestionParserRuleCall_3_0 = (RuleCall)cQuestionsAssignment_3.eContents().get(0);
		
		//Page:
		//	"Page" (("title:" title=EString)? & ("visibleIf:" visibleIf=EString)?) questions+=Question questions+=Question*;
		public ParserRule getRule() { return rule; }

		//"Page" (("title:" title=EString)? & ("visibleIf:" visibleIf=EString)?) questions+=Question questions+=Question*
		public Group getGroup() { return cGroup; }

		//"Page"
		public Keyword getPageKeyword_0() { return cPageKeyword_0; }

		//("title:" title=EString)? & ("visibleIf:" visibleIf=EString)?
		public UnorderedGroup getUnorderedGroup_1() { return cUnorderedGroup_1; }

		//("title:" title=EString)?
		public Group getGroup_1_0() { return cGroup_1_0; }

		//"title:"
		public Keyword getTitleKeyword_1_0_0() { return cTitleKeyword_1_0_0; }

		//title=EString
		public Assignment getTitleAssignment_1_0_1() { return cTitleAssignment_1_0_1; }

		//EString
		public RuleCall getTitleEStringParserRuleCall_1_0_1_0() { return cTitleEStringParserRuleCall_1_0_1_0; }

		//("visibleIf:" visibleIf=EString)?
		public Group getGroup_1_1() { return cGroup_1_1; }

		//"visibleIf:"
		public Keyword getVisibleIfKeyword_1_1_0() { return cVisibleIfKeyword_1_1_0; }

		//visibleIf=EString
		public Assignment getVisibleIfAssignment_1_1_1() { return cVisibleIfAssignment_1_1_1; }

		//EString
		public RuleCall getVisibleIfEStringParserRuleCall_1_1_1_0() { return cVisibleIfEStringParserRuleCall_1_1_1_0; }

		//questions+=Question
		public Assignment getQuestionsAssignment_2() { return cQuestionsAssignment_2; }

		//Question
		public RuleCall getQuestionsQuestionParserRuleCall_2_0() { return cQuestionsQuestionParserRuleCall_2_0; }

		//questions+=Question*
		public Assignment getQuestionsAssignment_3() { return cQuestionsAssignment_3; }

		//Question
		public RuleCall getQuestionsQuestionParserRuleCall_3_0() { return cQuestionsQuestionParserRuleCall_3_0; }
	}

	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//	"-"? INT;
		public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//	"true" | "false";
		public ParserRule getRule() { return rule; }

		//"true" | "false"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"true"
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }

		//"false"
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}

	public class QuestionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Question");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cQuestionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1 = (UnorderedGroup)cGroup.eContents().get(1);
		private final Assignment cIsRequiredAssignment_1_0 = (Assignment)cUnorderedGroup_1.eContents().get(0);
		private final Keyword cIsRequiredRequiredKeyword_1_0_0 = (Keyword)cIsRequiredAssignment_1_0.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cUnorderedGroup_1.eContents().get(1);
		private final Keyword cTypeKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Assignment cTypeAssignment_1_1_1 = (Assignment)cGroup_1_1.eContents().get(1);
		private final RuleCall cTypeQuestionTypeEnumRuleCall_1_1_1_0 = (RuleCall)cTypeAssignment_1_1_1.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cUnorderedGroup_1.eContents().get(2);
		private final Keyword cTitleKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Assignment cTitleAssignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final RuleCall cTitleEStringParserRuleCall_1_2_1_0 = (RuleCall)cTitleAssignment_1_2_1.eContents().get(0);
		private final Group cGroup_1_3 = (Group)cUnorderedGroup_1.eContents().get(3);
		private final Keyword cRangeStartKeyword_1_3_0 = (Keyword)cGroup_1_3.eContents().get(0);
		private final Assignment cRangeStartAssignment_1_3_1 = (Assignment)cGroup_1_3.eContents().get(1);
		private final RuleCall cRangeStartEIntParserRuleCall_1_3_1_0 = (RuleCall)cRangeStartAssignment_1_3_1.eContents().get(0);
		private final Group cGroup_1_4 = (Group)cUnorderedGroup_1.eContents().get(4);
		private final Keyword cRangeEndKeyword_1_4_0 = (Keyword)cGroup_1_4.eContents().get(0);
		private final Assignment cRangeEndAssignment_1_4_1 = (Assignment)cGroup_1_4.eContents().get(1);
		private final RuleCall cRangeEndEIntParserRuleCall_1_4_1_0 = (RuleCall)cRangeEndAssignment_1_4_1.eContents().get(0);
		private final Group cGroup_1_5 = (Group)cUnorderedGroup_1.eContents().get(5);
		private final Keyword cTextInputTypeKeyword_1_5_0 = (Keyword)cGroup_1_5.eContents().get(0);
		private final Assignment cInputTypeAssignment_1_5_1 = (Assignment)cGroup_1_5.eContents().get(1);
		private final RuleCall cInputTypeTextInputTypeEnumRuleCall_1_5_1_0 = (RuleCall)cInputTypeAssignment_1_5_1.eContents().get(0);
		private final Group cGroup_1_6 = (Group)cUnorderedGroup_1.eContents().get(6);
		private final Keyword cVisibleIfKeyword_1_6_0 = (Keyword)cGroup_1_6.eContents().get(0);
		private final Assignment cVisibleIfAssignment_1_6_1 = (Assignment)cGroup_1_6.eContents().get(1);
		private final RuleCall cVisibleIfEStringParserRuleCall_1_6_1_0 = (RuleCall)cVisibleIfAssignment_1_6_1.eContents().get(0);
		private final Group cGroup_1_7 = (Group)cUnorderedGroup_1.eContents().get(7);
		private final Keyword cPlaceholderKeyword_1_7_0 = (Keyword)cGroup_1_7.eContents().get(0);
		private final Assignment cPlaceholderAssignment_1_7_1 = (Assignment)cGroup_1_7.eContents().get(1);
		private final RuleCall cPlaceholderEStringParserRuleCall_1_7_1_0 = (RuleCall)cPlaceholderAssignment_1_7_1.eContents().get(0);
		private final Group cGroup_1_8 = (Group)cUnorderedGroup_1.eContents().get(8);
		private final Keyword cChoicesKeyword_1_8_0 = (Keyword)cGroup_1_8.eContents().get(0);
		private final Assignment cChoicesAssignment_1_8_1 = (Assignment)cGroup_1_8.eContents().get(1);
		private final RuleCall cChoicesEStringParserRuleCall_1_8_1_0 = (RuleCall)cChoicesAssignment_1_8_1.eContents().get(0);
		private final Group cGroup_1_8_2 = (Group)cGroup_1_8.eContents().get(2);
		private final Keyword cCommaKeyword_1_8_2_0 = (Keyword)cGroup_1_8_2.eContents().get(0);
		private final Assignment cChoicesAssignment_1_8_2_1 = (Assignment)cGroup_1_8_2.eContents().get(1);
		private final RuleCall cChoicesEStringParserRuleCall_1_8_2_1_0 = (RuleCall)cChoicesAssignment_1_8_2_1.eContents().get(0);
		private final Group cGroup_1_9 = (Group)cUnorderedGroup_1.eContents().get(9);
		private final Keyword cColCountKeyword_1_9_0 = (Keyword)cGroup_1_9.eContents().get(0);
		private final Assignment cColCountAssignment_1_9_1 = (Assignment)cGroup_1_9.eContents().get(1);
		private final RuleCall cColCountEIntParserRuleCall_1_9_1_0 = (RuleCall)cColCountAssignment_1_9_1.eContents().get(0);
		private final Group cGroup_1_10 = (Group)cUnorderedGroup_1.eContents().get(10);
		private final Keyword cQuestionNameKeyword_1_10_0 = (Keyword)cGroup_1_10.eContents().get(0);
		private final Assignment cQuestionNameAssignment_1_10_1 = (Assignment)cGroup_1_10.eContents().get(1);
		private final RuleCall cQuestionNameEStringParserRuleCall_1_10_1_0 = (RuleCall)cQuestionNameAssignment_1_10_1.eContents().get(0);
		private final Group cGroup_1_11 = (Group)cUnorderedGroup_1.eContents().get(11);
		private final Keyword cCommentRowsKeyword_1_11_0 = (Keyword)cGroup_1_11.eContents().get(0);
		private final Assignment cRowsAssignment_1_11_1 = (Assignment)cGroup_1_11.eContents().get(1);
		private final RuleCall cRowsEIntParserRuleCall_1_11_1_0 = (RuleCall)cRowsAssignment_1_11_1.eContents().get(0);
		private final Group cGroup_1_12 = (Group)cUnorderedGroup_1.eContents().get(12);
		private final Keyword cRatingMinDescriptionKeyword_1_12_0 = (Keyword)cGroup_1_12.eContents().get(0);
		private final Assignment cMininumRateDescriptionAssignment_1_12_1 = (Assignment)cGroup_1_12.eContents().get(1);
		private final RuleCall cMininumRateDescriptionEStringParserRuleCall_1_12_1_0 = (RuleCall)cMininumRateDescriptionAssignment_1_12_1.eContents().get(0);
		private final Group cGroup_1_13 = (Group)cUnorderedGroup_1.eContents().get(13);
		private final Keyword cRatingMaxDescriptionKeyword_1_13_0 = (Keyword)cGroup_1_13.eContents().get(0);
		private final Assignment cMaximumRateDescriptionAssignment_1_13_1 = (Assignment)cGroup_1_13.eContents().get(1);
		private final RuleCall cMaximumRateDescriptionEStringParserRuleCall_1_13_1_0 = (RuleCall)cMaximumRateDescriptionAssignment_1_13_1.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_2 = (UnorderedGroup)cGroup.eContents().get(2);
		private final Group cGroup_2_0 = (Group)cUnorderedGroup_2.eContents().get(0);
		private final Keyword cMatrixRowsKeyword_2_0_0 = (Keyword)cGroup_2_0.eContents().get(0);
		private final Assignment cMatrixRowsAssignment_2_0_1 = (Assignment)cGroup_2_0.eContents().get(1);
		private final RuleCall cMatrixRowsTextValueParserRuleCall_2_0_1_0 = (RuleCall)cMatrixRowsAssignment_2_0_1.eContents().get(0);
		private final Group cGroup_2_0_2 = (Group)cGroup_2_0.eContents().get(2);
		private final Keyword cCommaKeyword_2_0_2_0 = (Keyword)cGroup_2_0_2.eContents().get(0);
		private final Assignment cMatrixRowsAssignment_2_0_2_1 = (Assignment)cGroup_2_0_2.eContents().get(1);
		private final RuleCall cMatrixRowsTextValueParserRuleCall_2_0_2_1_0 = (RuleCall)cMatrixRowsAssignment_2_0_2_1.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cUnorderedGroup_2.eContents().get(1);
		private final Keyword cMultiTextItemsKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cMultiTextItemsAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cMultiTextItemsMultiTextItemParserRuleCall_2_1_1_0 = (RuleCall)cMultiTextItemsAssignment_2_1_1.eContents().get(0);
		private final Assignment cMultiTextItemsAssignment_2_1_2 = (Assignment)cGroup_2_1.eContents().get(2);
		private final RuleCall cMultiTextItemsMultiTextItemParserRuleCall_2_1_2_0 = (RuleCall)cMultiTextItemsAssignment_2_1_2.eContents().get(0);
		private final Group cGroup_2_2 = (Group)cUnorderedGroup_2.eContents().get(2);
		private final Keyword cMatrixColumnsKeyword_2_2_0 = (Keyword)cGroup_2_2.eContents().get(0);
		private final Assignment cMatrixColumnsAssignment_2_2_1 = (Assignment)cGroup_2_2.eContents().get(1);
		private final RuleCall cMatrixColumnsTextValueParserRuleCall_2_2_1_0 = (RuleCall)cMatrixColumnsAssignment_2_2_1.eContents().get(0);
		private final Group cGroup_2_2_2 = (Group)cGroup_2_2.eContents().get(2);
		private final Keyword cCommaKeyword_2_2_2_0 = (Keyword)cGroup_2_2_2.eContents().get(0);
		private final Assignment cMatrixColumnsAssignment_2_2_2_1 = (Assignment)cGroup_2_2_2.eContents().get(1);
		private final RuleCall cMatrixColumnsTextValueParserRuleCall_2_2_2_1_0 = (RuleCall)cMatrixColumnsAssignment_2_2_2_1.eContents().get(0);
		
		//Question:
		//	"Question" (isRequired?="required"? & "type:" type=QuestionType & "title:" title=EString & ("rangeStart:"
		//	rangeStart=EInt)? & ("rangeEnd:" rangeEnd=EInt)? & ("textInputType:" inputType=TextInputType)? & ("visibleIf:"
		//	visibleIf=EString)? & ("placeholder:" placeholder=EString)? & ("choices:" choices+=EString ("," choices+=EString)*)?
		//	& ("colCount:" colCount=EInt)? & ("questionName:" questionName=EString)? & ("commentRows:" rows=EInt)? &
		//	("ratingMinDescription:" mininumRateDescription=EString)? & ("ratingMaxDescription:"
		//	maximumRateDescription=EString)?) (("matrixRows:" matrixRows+=TextValue ("," matrixRows+=TextValue)*)? &
		//	("multiTextItems:" multiTextItems+=MultiTextItem multiTextItems+=MultiTextItem*)? & ("matrixColumns:"
		//	matrixColumns+=TextValue ("," matrixColumns+=TextValue)*)?);
		public ParserRule getRule() { return rule; }

		//"Question" (isRequired?="required"? & "type:" type=QuestionType & "title:" title=EString & ("rangeStart:"
		//rangeStart=EInt)? & ("rangeEnd:" rangeEnd=EInt)? & ("textInputType:" inputType=TextInputType)? & ("visibleIf:"
		//visibleIf=EString)? & ("placeholder:" placeholder=EString)? & ("choices:" choices+=EString ("," choices+=EString)*)? &
		//("colCount:" colCount=EInt)? & ("questionName:" questionName=EString)? & ("commentRows:" rows=EInt)? &
		//("ratingMinDescription:" mininumRateDescription=EString)? & ("ratingMaxDescription:" maximumRateDescription=EString)?)
		//(("matrixRows:" matrixRows+=TextValue ("," matrixRows+=TextValue)*)? & ("multiTextItems:"
		//multiTextItems+=MultiTextItem multiTextItems+=MultiTextItem*)? & ("matrixColumns:" matrixColumns+=TextValue (","
		//matrixColumns+=TextValue)*)?)
		public Group getGroup() { return cGroup; }

		//"Question"
		public Keyword getQuestionKeyword_0() { return cQuestionKeyword_0; }

		//isRequired?="required"? & "type:" type=QuestionType & "title:" title=EString & ("rangeStart:" rangeStart=EInt)? &
		//("rangeEnd:" rangeEnd=EInt)? & ("textInputType:" inputType=TextInputType)? & ("visibleIf:" visibleIf=EString)? &
		//("placeholder:" placeholder=EString)? & ("choices:" choices+=EString ("," choices+=EString)*)? & ("colCount:"
		//colCount=EInt)? & ("questionName:" questionName=EString)? & ("commentRows:" rows=EInt)? & ("ratingMinDescription:"
		//mininumRateDescription=EString)? & ("ratingMaxDescription:" maximumRateDescription=EString)?
		public UnorderedGroup getUnorderedGroup_1() { return cUnorderedGroup_1; }

		//isRequired?="required"?
		public Assignment getIsRequiredAssignment_1_0() { return cIsRequiredAssignment_1_0; }

		//"required"
		public Keyword getIsRequiredRequiredKeyword_1_0_0() { return cIsRequiredRequiredKeyword_1_0_0; }

		//"type:" type=QuestionType
		public Group getGroup_1_1() { return cGroup_1_1; }

		//"type:"
		public Keyword getTypeKeyword_1_1_0() { return cTypeKeyword_1_1_0; }

		//type=QuestionType
		public Assignment getTypeAssignment_1_1_1() { return cTypeAssignment_1_1_1; }

		//QuestionType
		public RuleCall getTypeQuestionTypeEnumRuleCall_1_1_1_0() { return cTypeQuestionTypeEnumRuleCall_1_1_1_0; }

		//"title:" title=EString
		public Group getGroup_1_2() { return cGroup_1_2; }

		//"title:"
		public Keyword getTitleKeyword_1_2_0() { return cTitleKeyword_1_2_0; }

		//title=EString
		public Assignment getTitleAssignment_1_2_1() { return cTitleAssignment_1_2_1; }

		//EString
		public RuleCall getTitleEStringParserRuleCall_1_2_1_0() { return cTitleEStringParserRuleCall_1_2_1_0; }

		//("rangeStart:" rangeStart=EInt)?
		public Group getGroup_1_3() { return cGroup_1_3; }

		//"rangeStart:"
		public Keyword getRangeStartKeyword_1_3_0() { return cRangeStartKeyword_1_3_0; }

		//rangeStart=EInt
		public Assignment getRangeStartAssignment_1_3_1() { return cRangeStartAssignment_1_3_1; }

		//EInt
		public RuleCall getRangeStartEIntParserRuleCall_1_3_1_0() { return cRangeStartEIntParserRuleCall_1_3_1_0; }

		//("rangeEnd:" rangeEnd=EInt)?
		public Group getGroup_1_4() { return cGroup_1_4; }

		//"rangeEnd:"
		public Keyword getRangeEndKeyword_1_4_0() { return cRangeEndKeyword_1_4_0; }

		//rangeEnd=EInt
		public Assignment getRangeEndAssignment_1_4_1() { return cRangeEndAssignment_1_4_1; }

		//EInt
		public RuleCall getRangeEndEIntParserRuleCall_1_4_1_0() { return cRangeEndEIntParserRuleCall_1_4_1_0; }

		//("textInputType:" inputType=TextInputType)?
		public Group getGroup_1_5() { return cGroup_1_5; }

		//"textInputType:"
		public Keyword getTextInputTypeKeyword_1_5_0() { return cTextInputTypeKeyword_1_5_0; }

		//inputType=TextInputType
		public Assignment getInputTypeAssignment_1_5_1() { return cInputTypeAssignment_1_5_1; }

		//TextInputType
		public RuleCall getInputTypeTextInputTypeEnumRuleCall_1_5_1_0() { return cInputTypeTextInputTypeEnumRuleCall_1_5_1_0; }

		//("visibleIf:" visibleIf=EString)?
		public Group getGroup_1_6() { return cGroup_1_6; }

		//"visibleIf:"
		public Keyword getVisibleIfKeyword_1_6_0() { return cVisibleIfKeyword_1_6_0; }

		//visibleIf=EString
		public Assignment getVisibleIfAssignment_1_6_1() { return cVisibleIfAssignment_1_6_1; }

		//EString
		public RuleCall getVisibleIfEStringParserRuleCall_1_6_1_0() { return cVisibleIfEStringParserRuleCall_1_6_1_0; }

		//("placeholder:" placeholder=EString)?
		public Group getGroup_1_7() { return cGroup_1_7; }

		//"placeholder:"
		public Keyword getPlaceholderKeyword_1_7_0() { return cPlaceholderKeyword_1_7_0; }

		//placeholder=EString
		public Assignment getPlaceholderAssignment_1_7_1() { return cPlaceholderAssignment_1_7_1; }

		//EString
		public RuleCall getPlaceholderEStringParserRuleCall_1_7_1_0() { return cPlaceholderEStringParserRuleCall_1_7_1_0; }

		//("choices:" choices+=EString ("," choices+=EString)*)?
		public Group getGroup_1_8() { return cGroup_1_8; }

		//"choices:"
		public Keyword getChoicesKeyword_1_8_0() { return cChoicesKeyword_1_8_0; }

		//choices+=EString
		public Assignment getChoicesAssignment_1_8_1() { return cChoicesAssignment_1_8_1; }

		//EString
		public RuleCall getChoicesEStringParserRuleCall_1_8_1_0() { return cChoicesEStringParserRuleCall_1_8_1_0; }

		//("," choices+=EString)*
		public Group getGroup_1_8_2() { return cGroup_1_8_2; }

		//","
		public Keyword getCommaKeyword_1_8_2_0() { return cCommaKeyword_1_8_2_0; }

		//choices+=EString
		public Assignment getChoicesAssignment_1_8_2_1() { return cChoicesAssignment_1_8_2_1; }

		//EString
		public RuleCall getChoicesEStringParserRuleCall_1_8_2_1_0() { return cChoicesEStringParserRuleCall_1_8_2_1_0; }

		//("colCount:" colCount=EInt)?
		public Group getGroup_1_9() { return cGroup_1_9; }

		//"colCount:"
		public Keyword getColCountKeyword_1_9_0() { return cColCountKeyword_1_9_0; }

		//colCount=EInt
		public Assignment getColCountAssignment_1_9_1() { return cColCountAssignment_1_9_1; }

		//EInt
		public RuleCall getColCountEIntParserRuleCall_1_9_1_0() { return cColCountEIntParserRuleCall_1_9_1_0; }

		//("questionName:" questionName=EString)?
		public Group getGroup_1_10() { return cGroup_1_10; }

		//"questionName:"
		public Keyword getQuestionNameKeyword_1_10_0() { return cQuestionNameKeyword_1_10_0; }

		//questionName=EString
		public Assignment getQuestionNameAssignment_1_10_1() { return cQuestionNameAssignment_1_10_1; }

		//EString
		public RuleCall getQuestionNameEStringParserRuleCall_1_10_1_0() { return cQuestionNameEStringParserRuleCall_1_10_1_0; }

		//("commentRows:" rows=EInt)?
		public Group getGroup_1_11() { return cGroup_1_11; }

		//"commentRows:"
		public Keyword getCommentRowsKeyword_1_11_0() { return cCommentRowsKeyword_1_11_0; }

		//rows=EInt
		public Assignment getRowsAssignment_1_11_1() { return cRowsAssignment_1_11_1; }

		//EInt
		public RuleCall getRowsEIntParserRuleCall_1_11_1_0() { return cRowsEIntParserRuleCall_1_11_1_0; }

		//("ratingMinDescription:" mininumRateDescription=EString)?
		public Group getGroup_1_12() { return cGroup_1_12; }

		//"ratingMinDescription:"
		public Keyword getRatingMinDescriptionKeyword_1_12_0() { return cRatingMinDescriptionKeyword_1_12_0; }

		//mininumRateDescription=EString
		public Assignment getMininumRateDescriptionAssignment_1_12_1() { return cMininumRateDescriptionAssignment_1_12_1; }

		//EString
		public RuleCall getMininumRateDescriptionEStringParserRuleCall_1_12_1_0() { return cMininumRateDescriptionEStringParserRuleCall_1_12_1_0; }

		//("ratingMaxDescription:" maximumRateDescription=EString)?
		public Group getGroup_1_13() { return cGroup_1_13; }

		//"ratingMaxDescription:"
		public Keyword getRatingMaxDescriptionKeyword_1_13_0() { return cRatingMaxDescriptionKeyword_1_13_0; }

		//maximumRateDescription=EString
		public Assignment getMaximumRateDescriptionAssignment_1_13_1() { return cMaximumRateDescriptionAssignment_1_13_1; }

		//EString
		public RuleCall getMaximumRateDescriptionEStringParserRuleCall_1_13_1_0() { return cMaximumRateDescriptionEStringParserRuleCall_1_13_1_0; }

		//("matrixRows:" matrixRows+=TextValue ("," matrixRows+=TextValue)*)? & ("multiTextItems:" multiTextItems+=MultiTextItem
		//multiTextItems+=MultiTextItem*)? & ("matrixColumns:" matrixColumns+=TextValue ("," matrixColumns+=TextValue)*)?
		public UnorderedGroup getUnorderedGroup_2() { return cUnorderedGroup_2; }

		//("matrixRows:" matrixRows+=TextValue ("," matrixRows+=TextValue)*)?
		public Group getGroup_2_0() { return cGroup_2_0; }

		//"matrixRows:"
		public Keyword getMatrixRowsKeyword_2_0_0() { return cMatrixRowsKeyword_2_0_0; }

		//matrixRows+=TextValue
		public Assignment getMatrixRowsAssignment_2_0_1() { return cMatrixRowsAssignment_2_0_1; }

		//TextValue
		public RuleCall getMatrixRowsTextValueParserRuleCall_2_0_1_0() { return cMatrixRowsTextValueParserRuleCall_2_0_1_0; }

		//("," matrixRows+=TextValue)*
		public Group getGroup_2_0_2() { return cGroup_2_0_2; }

		//","
		public Keyword getCommaKeyword_2_0_2_0() { return cCommaKeyword_2_0_2_0; }

		//matrixRows+=TextValue
		public Assignment getMatrixRowsAssignment_2_0_2_1() { return cMatrixRowsAssignment_2_0_2_1; }

		//TextValue
		public RuleCall getMatrixRowsTextValueParserRuleCall_2_0_2_1_0() { return cMatrixRowsTextValueParserRuleCall_2_0_2_1_0; }

		//("multiTextItems:" multiTextItems+=MultiTextItem multiTextItems+=MultiTextItem*)?
		public Group getGroup_2_1() { return cGroup_2_1; }

		//"multiTextItems:"
		public Keyword getMultiTextItemsKeyword_2_1_0() { return cMultiTextItemsKeyword_2_1_0; }

		//multiTextItems+=MultiTextItem
		public Assignment getMultiTextItemsAssignment_2_1_1() { return cMultiTextItemsAssignment_2_1_1; }

		//MultiTextItem
		public RuleCall getMultiTextItemsMultiTextItemParserRuleCall_2_1_1_0() { return cMultiTextItemsMultiTextItemParserRuleCall_2_1_1_0; }

		//multiTextItems+=MultiTextItem*
		public Assignment getMultiTextItemsAssignment_2_1_2() { return cMultiTextItemsAssignment_2_1_2; }

		//MultiTextItem
		public RuleCall getMultiTextItemsMultiTextItemParserRuleCall_2_1_2_0() { return cMultiTextItemsMultiTextItemParserRuleCall_2_1_2_0; }

		//("matrixColumns:" matrixColumns+=TextValue ("," matrixColumns+=TextValue)*)?
		public Group getGroup_2_2() { return cGroup_2_2; }

		//"matrixColumns:"
		public Keyword getMatrixColumnsKeyword_2_2_0() { return cMatrixColumnsKeyword_2_2_0; }

		//matrixColumns+=TextValue
		public Assignment getMatrixColumnsAssignment_2_2_1() { return cMatrixColumnsAssignment_2_2_1; }

		//TextValue
		public RuleCall getMatrixColumnsTextValueParserRuleCall_2_2_1_0() { return cMatrixColumnsTextValueParserRuleCall_2_2_1_0; }

		//("," matrixColumns+=TextValue)*
		public Group getGroup_2_2_2() { return cGroup_2_2_2; }

		//","
		public Keyword getCommaKeyword_2_2_2_0() { return cCommaKeyword_2_2_2_0; }

		//matrixColumns+=TextValue
		public Assignment getMatrixColumnsAssignment_2_2_2_1() { return cMatrixColumnsAssignment_2_2_2_1; }

		//TextValue
		public RuleCall getMatrixColumnsTextValueParserRuleCall_2_2_2_1_0() { return cMatrixColumnsTextValueParserRuleCall_2_2_2_1_0; }
	}

	public class TextValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TextValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTextKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTextAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTextEStringParserRuleCall_2_0 = (RuleCall)cTextAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cValueKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cValueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValueEStringParserRuleCall_3_1_0 = (RuleCall)cValueAssignment_3_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//TextValue:
		//	"(" "text:" text=EString ("value:" value=EString)? ")";
		public ParserRule getRule() { return rule; }

		//"(" "text:" text=EString ("value:" value=EString)? ")"
		public Group getGroup() { return cGroup; }

		//"("
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }

		//"text:"
		public Keyword getTextKeyword_1() { return cTextKeyword_1; }

		//text=EString
		public Assignment getTextAssignment_2() { return cTextAssignment_2; }

		//EString
		public RuleCall getTextEStringParserRuleCall_2_0() { return cTextEStringParserRuleCall_2_0; }

		//("value:" value=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"value:"
		public Keyword getValueKeyword_3_0() { return cValueKeyword_3_0; }

		//value=EString
		public Assignment getValueAssignment_3_1() { return cValueAssignment_3_1; }

		//EString
		public RuleCall getValueEStringParserRuleCall_3_1_0() { return cValueEStringParserRuleCall_3_1_0; }

		//")"
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}

	public class MultiTextItemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MultiTextItem");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSubtitleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTitleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTitleEStringParserRuleCall_1_0 = (RuleCall)cTitleAssignment_1.eContents().get(0);
		
		//MultiTextItem:
		//	"subtitle:" title=EString;
		public ParserRule getRule() { return rule; }

		//"subtitle:" title=EString
		public Group getGroup() { return cGroup; }

		//"subtitle:"
		public Keyword getSubtitleKeyword_0() { return cSubtitleKeyword_0; }

		//title=EString
		public Assignment getTitleAssignment_1() { return cTitleAssignment_1; }

		//EString
		public RuleCall getTitleEStringParserRuleCall_1_0() { return cTitleEStringParserRuleCall_1_0; }
	}
	
	
	public class TitleLocationElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "TitleLocation");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cTopEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cTopTopKeyword_0_0 = (Keyword)cTopEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBottomEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBottomBottomKeyword_1_0 = (Keyword)cBottomEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum TitleLocation:
		//	top | bottom;
		public EnumRule getRule() { return rule; }

		//top | bottom
		public Alternatives getAlternatives() { return cAlternatives; }

		//top
		public EnumLiteralDeclaration getTopEnumLiteralDeclaration_0() { return cTopEnumLiteralDeclaration_0; }

		//"top"
		public Keyword getTopTopKeyword_0_0() { return cTopTopKeyword_0_0; }

		//bottom
		public EnumLiteralDeclaration getBottomEnumLiteralDeclaration_1() { return cBottomEnumLiteralDeclaration_1; }

		//"bottom"
		public Keyword getBottomBottomKeyword_1_0() { return cBottomBottomKeyword_1_0; }
	}

	public class ProgressBarLocationElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "ProgressBarLocation");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cTopEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cTopTopKeyword_0_0 = (Keyword)cTopEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cOffEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cOffOffKeyword_1_0 = (Keyword)cOffEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cBottomEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cBottomBottomKeyword_2_0 = (Keyword)cBottomEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum ProgressBarLocation:
		//	top | off | bottom;
		public EnumRule getRule() { return rule; }

		//top | off | bottom
		public Alternatives getAlternatives() { return cAlternatives; }

		//top
		public EnumLiteralDeclaration getTopEnumLiteralDeclaration_0() { return cTopEnumLiteralDeclaration_0; }

		//"top"
		public Keyword getTopTopKeyword_0_0() { return cTopTopKeyword_0_0; }

		//off
		public EnumLiteralDeclaration getOffEnumLiteralDeclaration_1() { return cOffEnumLiteralDeclaration_1; }

		//"off"
		public Keyword getOffOffKeyword_1_0() { return cOffOffKeyword_1_0; }

		//bottom
		public EnumLiteralDeclaration getBottomEnumLiteralDeclaration_2() { return cBottomEnumLiteralDeclaration_2; }

		//"bottom"
		public Keyword getBottomBottomKeyword_2_0() { return cBottomBottomKeyword_2_0; }
	}

	public class QuestionTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "QuestionType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cTextEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cTextTextKeyword_0_0 = (Keyword)cTextEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cRadiogroupEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cRadiogroupRadiogroupKeyword_1_0 = (Keyword)cRadiogroupEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cCheckboxEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cCheckboxCheckboxKeyword_2_0 = (Keyword)cCheckboxEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cDropdownEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cDropdownDropdownKeyword_3_0 = (Keyword)cDropdownEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cCommentEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cCommentCommentKeyword_4_0 = (Keyword)cCommentEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cMatrixEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cMatrixMatrixKeyword_5_0 = (Keyword)cMatrixEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cMultipleTextEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cMultipleTextMultipleTextKeyword_6_0 = (Keyword)cMultipleTextEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cRatingEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cRatingRatingKeyword_7_0 = (Keyword)cRatingEnumLiteralDeclaration_7.eContents().get(0);
		
		//enum QuestionType:
		//	text | radiogroup | checkbox | dropdown | comment | matrix | multipleText | rating;
		public EnumRule getRule() { return rule; }

		//text | radiogroup | checkbox | dropdown | comment | matrix | multipleText | rating
		public Alternatives getAlternatives() { return cAlternatives; }

		//text
		public EnumLiteralDeclaration getTextEnumLiteralDeclaration_0() { return cTextEnumLiteralDeclaration_0; }

		//"text"
		public Keyword getTextTextKeyword_0_0() { return cTextTextKeyword_0_0; }

		//radiogroup
		public EnumLiteralDeclaration getRadiogroupEnumLiteralDeclaration_1() { return cRadiogroupEnumLiteralDeclaration_1; }

		//"radiogroup"
		public Keyword getRadiogroupRadiogroupKeyword_1_0() { return cRadiogroupRadiogroupKeyword_1_0; }

		//checkbox
		public EnumLiteralDeclaration getCheckboxEnumLiteralDeclaration_2() { return cCheckboxEnumLiteralDeclaration_2; }

		//"checkbox"
		public Keyword getCheckboxCheckboxKeyword_2_0() { return cCheckboxCheckboxKeyword_2_0; }

		//dropdown
		public EnumLiteralDeclaration getDropdownEnumLiteralDeclaration_3() { return cDropdownEnumLiteralDeclaration_3; }

		//"dropdown"
		public Keyword getDropdownDropdownKeyword_3_0() { return cDropdownDropdownKeyword_3_0; }

		//comment
		public EnumLiteralDeclaration getCommentEnumLiteralDeclaration_4() { return cCommentEnumLiteralDeclaration_4; }

		//"comment"
		public Keyword getCommentCommentKeyword_4_0() { return cCommentCommentKeyword_4_0; }

		//matrix
		public EnumLiteralDeclaration getMatrixEnumLiteralDeclaration_5() { return cMatrixEnumLiteralDeclaration_5; }

		//"matrix"
		public Keyword getMatrixMatrixKeyword_5_0() { return cMatrixMatrixKeyword_5_0; }

		//multipleText
		public EnumLiteralDeclaration getMultipleTextEnumLiteralDeclaration_6() { return cMultipleTextEnumLiteralDeclaration_6; }

		//"multipleText"
		public Keyword getMultipleTextMultipleTextKeyword_6_0() { return cMultipleTextMultipleTextKeyword_6_0; }

		//rating
		public EnumLiteralDeclaration getRatingEnumLiteralDeclaration_7() { return cRatingEnumLiteralDeclaration_7; }

		//"rating"
		public Keyword getRatingRatingKeyword_7_0() { return cRatingRatingKeyword_7_0; }
	}

	public class TextInputTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "TextInputType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cTextEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cTextTextKeyword_0_0 = (Keyword)cTextEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cTimeEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cTimeTimeKeyword_1_0 = (Keyword)cTimeEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cRangeEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cRangeRangeKeyword_2_0 = (Keyword)cRangeEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cColorEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cColorColorKeyword_3_0 = (Keyword)cColorEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cDateEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cDateDateKeyword_4_0 = (Keyword)cDateEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cDatetimeEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cDatetimeDatetimeKeyword_5_0 = (Keyword)cDatetimeEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cEmailEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cEmailEmailKeyword_6_0 = (Keyword)cEmailEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cMonthEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cMonthMonthKeyword_7_0 = (Keyword)cMonthEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cNumberEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cNumberNumberKeyword_8_0 = (Keyword)cNumberEnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cPasswordEnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cPasswordPasswordKeyword_9_0 = (Keyword)cPasswordEnumLiteralDeclaration_9.eContents().get(0);
		private final EnumLiteralDeclaration cTelEnumLiteralDeclaration_10 = (EnumLiteralDeclaration)cAlternatives.eContents().get(10);
		private final Keyword cTelTelKeyword_10_0 = (Keyword)cTelEnumLiteralDeclaration_10.eContents().get(0);
		private final EnumLiteralDeclaration cUrlEnumLiteralDeclaration_11 = (EnumLiteralDeclaration)cAlternatives.eContents().get(11);
		private final Keyword cUrlUrlKeyword_11_0 = (Keyword)cUrlEnumLiteralDeclaration_11.eContents().get(0);
		private final EnumLiteralDeclaration cWeekEnumLiteralDeclaration_12 = (EnumLiteralDeclaration)cAlternatives.eContents().get(12);
		private final Keyword cWeekWeekKeyword_12_0 = (Keyword)cWeekEnumLiteralDeclaration_12.eContents().get(0);
		
		//enum TextInputType:
		//	text | time | range | color | date | datetime | email | month | number | password | tel | url | week;
		public EnumRule getRule() { return rule; }

		//text | time | range | color | date | datetime | email | month | number | password | tel | url | week
		public Alternatives getAlternatives() { return cAlternatives; }

		//text
		public EnumLiteralDeclaration getTextEnumLiteralDeclaration_0() { return cTextEnumLiteralDeclaration_0; }

		//"text"
		public Keyword getTextTextKeyword_0_0() { return cTextTextKeyword_0_0; }

		//time
		public EnumLiteralDeclaration getTimeEnumLiteralDeclaration_1() { return cTimeEnumLiteralDeclaration_1; }

		//"time"
		public Keyword getTimeTimeKeyword_1_0() { return cTimeTimeKeyword_1_0; }

		//range
		public EnumLiteralDeclaration getRangeEnumLiteralDeclaration_2() { return cRangeEnumLiteralDeclaration_2; }

		//"range"
		public Keyword getRangeRangeKeyword_2_0() { return cRangeRangeKeyword_2_0; }

		//color
		public EnumLiteralDeclaration getColorEnumLiteralDeclaration_3() { return cColorEnumLiteralDeclaration_3; }

		//"color"
		public Keyword getColorColorKeyword_3_0() { return cColorColorKeyword_3_0; }

		//date
		public EnumLiteralDeclaration getDateEnumLiteralDeclaration_4() { return cDateEnumLiteralDeclaration_4; }

		//"date"
		public Keyword getDateDateKeyword_4_0() { return cDateDateKeyword_4_0; }

		//datetime
		public EnumLiteralDeclaration getDatetimeEnumLiteralDeclaration_5() { return cDatetimeEnumLiteralDeclaration_5; }

		//"datetime"
		public Keyword getDatetimeDatetimeKeyword_5_0() { return cDatetimeDatetimeKeyword_5_0; }

		//email
		public EnumLiteralDeclaration getEmailEnumLiteralDeclaration_6() { return cEmailEnumLiteralDeclaration_6; }

		//"email"
		public Keyword getEmailEmailKeyword_6_0() { return cEmailEmailKeyword_6_0; }

		//month
		public EnumLiteralDeclaration getMonthEnumLiteralDeclaration_7() { return cMonthEnumLiteralDeclaration_7; }

		//"month"
		public Keyword getMonthMonthKeyword_7_0() { return cMonthMonthKeyword_7_0; }

		//number
		public EnumLiteralDeclaration getNumberEnumLiteralDeclaration_8() { return cNumberEnumLiteralDeclaration_8; }

		//"number"
		public Keyword getNumberNumberKeyword_8_0() { return cNumberNumberKeyword_8_0; }

		//password
		public EnumLiteralDeclaration getPasswordEnumLiteralDeclaration_9() { return cPasswordEnumLiteralDeclaration_9; }

		//"password"
		public Keyword getPasswordPasswordKeyword_9_0() { return cPasswordPasswordKeyword_9_0; }

		//tel
		public EnumLiteralDeclaration getTelEnumLiteralDeclaration_10() { return cTelEnumLiteralDeclaration_10; }

		//"tel"
		public Keyword getTelTelKeyword_10_0() { return cTelTelKeyword_10_0; }

		//url
		public EnumLiteralDeclaration getUrlEnumLiteralDeclaration_11() { return cUrlEnumLiteralDeclaration_11; }

		//"url"
		public Keyword getUrlUrlKeyword_11_0() { return cUrlUrlKeyword_11_0; }

		//week
		public EnumLiteralDeclaration getWeekEnumLiteralDeclaration_12() { return cWeekEnumLiteralDeclaration_12; }

		//"week"
		public Keyword getWeekWeekKeyword_12_0() { return cWeekWeekKeyword_12_0; }
	}
	
	private SurveyElements pSurvey;
	private EStringElements pEString;
	private PageElements pPage;
	private EIntElements pEInt;
	private TitleLocationElements unknownRuleTitleLocation;
	private EBooleanElements pEBoolean;
	private ProgressBarLocationElements unknownRuleProgressBarLocation;
	private QuestionElements pQuestion;
	private QuestionTypeElements unknownRuleQuestionType;
	private TextInputTypeElements unknownRuleTextInputType;
	private TextValueElements pTextValue;
	private MultiTextItemElements pMultiTextItem;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public QueryITGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("xtext.QueryIT".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Survey:
	//	(hideNavigationButtons?="hideNavigationButtons"? & hidePageTitles?="hidePageTitles"? &
	//	hideQuestionNumbers?="hideQuestionNumbers"? & hidePageNumbers?="hidePageNumbers"? & ("author(s):" author+=EString
	//	("," author+=EString)*)? & ("title:" title=EString)? & ("timeLimit:" timeLimit=EInt)? & ("completedMessage:"
	//	completedMessage=EString)? & ("buttonNextText:" pageNextText=EString)? & ("buttonPrevText:" pagePrevText=EString)? &
	//	("buttonCompletedText:" completeText=EString)? & ("questionTitleLocation:" questionTitleLocation=TitleLocation)? &
	//	("progressBarLocation:" showProgressBar=ProgressBarLocation)?) pages+=Page pages+=Page*;
	public SurveyElements getSurveyAccess() {
		return (pSurvey != null) ? pSurvey : (pSurvey = new SurveyElements());
	}
	
	public ParserRule getSurveyRule() {
		return getSurveyAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return (pEString != null) ? pEString : (pEString = new EStringElements());
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//Page:
	//	"Page" (("title:" title=EString)? & ("visibleIf:" visibleIf=EString)?) questions+=Question questions+=Question*;
	public PageElements getPageAccess() {
		return (pPage != null) ? pPage : (pPage = new PageElements());
	}
	
	public ParserRule getPageRule() {
		return getPageAccess().getRule();
	}

	//EInt returns ecore::EInt:
	//	"-"? INT;
	public EIntElements getEIntAccess() {
		return (pEInt != null) ? pEInt : (pEInt = new EIntElements());
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	//enum TitleLocation:
	//	top | bottom;
	public TitleLocationElements getTitleLocationAccess() {
		return (unknownRuleTitleLocation != null) ? unknownRuleTitleLocation : (unknownRuleTitleLocation = new TitleLocationElements());
	}
	
	public EnumRule getTitleLocationRule() {
		return getTitleLocationAccess().getRule();
	}

	//EBoolean returns ecore::EBoolean:
	//	"true" | "false";
	public EBooleanElements getEBooleanAccess() {
		return (pEBoolean != null) ? pEBoolean : (pEBoolean = new EBooleanElements());
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}

	//enum ProgressBarLocation:
	//	top | off | bottom;
	public ProgressBarLocationElements getProgressBarLocationAccess() {
		return (unknownRuleProgressBarLocation != null) ? unknownRuleProgressBarLocation : (unknownRuleProgressBarLocation = new ProgressBarLocationElements());
	}
	
	public EnumRule getProgressBarLocationRule() {
		return getProgressBarLocationAccess().getRule();
	}

	//Question:
	//	"Question" (isRequired?="required"? & "type:" type=QuestionType & "title:" title=EString & ("rangeStart:"
	//	rangeStart=EInt)? & ("rangeEnd:" rangeEnd=EInt)? & ("textInputType:" inputType=TextInputType)? & ("visibleIf:"
	//	visibleIf=EString)? & ("placeholder:" placeholder=EString)? & ("choices:" choices+=EString ("," choices+=EString)*)?
	//	& ("colCount:" colCount=EInt)? & ("questionName:" questionName=EString)? & ("commentRows:" rows=EInt)? &
	//	("ratingMinDescription:" mininumRateDescription=EString)? & ("ratingMaxDescription:"
	//	maximumRateDescription=EString)?) (("matrixRows:" matrixRows+=TextValue ("," matrixRows+=TextValue)*)? &
	//	("multiTextItems:" multiTextItems+=MultiTextItem multiTextItems+=MultiTextItem*)? & ("matrixColumns:"
	//	matrixColumns+=TextValue ("," matrixColumns+=TextValue)*)?);
	public QuestionElements getQuestionAccess() {
		return (pQuestion != null) ? pQuestion : (pQuestion = new QuestionElements());
	}
	
	public ParserRule getQuestionRule() {
		return getQuestionAccess().getRule();
	}

	//enum QuestionType:
	//	text | radiogroup | checkbox | dropdown | comment | matrix | multipleText | rating;
	public QuestionTypeElements getQuestionTypeAccess() {
		return (unknownRuleQuestionType != null) ? unknownRuleQuestionType : (unknownRuleQuestionType = new QuestionTypeElements());
	}
	
	public EnumRule getQuestionTypeRule() {
		return getQuestionTypeAccess().getRule();
	}

	//enum TextInputType:
	//	text | time | range | color | date | datetime | email | month | number | password | tel | url | week;
	public TextInputTypeElements getTextInputTypeAccess() {
		return (unknownRuleTextInputType != null) ? unknownRuleTextInputType : (unknownRuleTextInputType = new TextInputTypeElements());
	}
	
	public EnumRule getTextInputTypeRule() {
		return getTextInputTypeAccess().getRule();
	}

	//TextValue:
	//	"(" "text:" text=EString ("value:" value=EString)? ")";
	public TextValueElements getTextValueAccess() {
		return (pTextValue != null) ? pTextValue : (pTextValue = new TextValueElements());
	}
	
	public ParserRule getTextValueRule() {
		return getTextValueAccess().getRule();
	}

	//MultiTextItem:
	//	"subtitle:" title=EString;
	public MultiTextItemElements getMultiTextItemAccess() {
		return (pMultiTextItem != null) ? pMultiTextItem : (pMultiTextItem = new MultiTextItemElements());
	}
	
	public ParserRule getMultiTextItemRule() {
		return getMultiTextItemAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
