/**
 * generated by Xtext
 */
package xtext.ui.contentassist;

import xtext.ui.contentassist.AbstractQueryITProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class QueryITProposalProvider extends AbstractQueryITProposalProvider {
}
