/*
 * generated by Xtext
 */
package xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import xtext.ui.internal.QueryITActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class QueryITExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return QueryITActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return QueryITActivator.getInstance().getInjector(QueryITActivator.XTEXT_QUERYIT);
	}
	
}
