/*
* generated by Xtext
*/
package xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class QueryITUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return xtext.ui.internal.QueryITActivator.getInstance().getInjector("xtext.QueryIT");
	}
	
}
