/*
* generated by Xtext
*/
package xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class QueryITStandaloneSetup extends QueryITStandaloneSetupGenerated{

	public static void doSetup() {
		new QueryITStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

