/*
 * generated by Xtext
 */
package xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QueryITRuntimeModule extends xtext.AbstractQueryITRuntimeModule {

}
