/*
* generated by Xtext
*/
package xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import xtext.services.QueryITGrammarAccess;

public class QueryITParser extends AbstractContentAssistParser {
	
	@Inject
	private QueryITGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected xtext.ui.contentassist.antlr.internal.InternalQueryITParser createParser() {
		xtext.ui.contentassist.antlr.internal.InternalQueryITParser result = new xtext.ui.contentassist.antlr.internal.InternalQueryITParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
					put(grammarAccess.getTitleLocationAccess().getAlternatives(), "rule__TitleLocation__Alternatives");
					put(grammarAccess.getProgressBarLocationAccess().getAlternatives(), "rule__ProgressBarLocation__Alternatives");
					put(grammarAccess.getQuestionTypeAccess().getAlternatives(), "rule__QuestionType__Alternatives");
					put(grammarAccess.getTextInputTypeAccess().getAlternatives(), "rule__TextInputType__Alternatives");
					put(grammarAccess.getSurveyAccess().getGroup(), "rule__Survey__Group__0");
					put(grammarAccess.getSurveyAccess().getGroup_0_4(), "rule__Survey__Group_0_4__0");
					put(grammarAccess.getSurveyAccess().getGroup_0_4_2(), "rule__Survey__Group_0_4_2__0");
					put(grammarAccess.getSurveyAccess().getGroup_0_5(), "rule__Survey__Group_0_5__0");
					put(grammarAccess.getSurveyAccess().getGroup_0_6(), "rule__Survey__Group_0_6__0");
					put(grammarAccess.getSurveyAccess().getGroup_0_7(), "rule__Survey__Group_0_7__0");
					put(grammarAccess.getSurveyAccess().getGroup_0_8(), "rule__Survey__Group_0_8__0");
					put(grammarAccess.getSurveyAccess().getGroup_0_9(), "rule__Survey__Group_0_9__0");
					put(grammarAccess.getSurveyAccess().getGroup_0_10(), "rule__Survey__Group_0_10__0");
					put(grammarAccess.getSurveyAccess().getGroup_0_11(), "rule__Survey__Group_0_11__0");
					put(grammarAccess.getSurveyAccess().getGroup_0_12(), "rule__Survey__Group_0_12__0");
					put(grammarAccess.getPageAccess().getGroup(), "rule__Page__Group__0");
					put(grammarAccess.getPageAccess().getGroup_1_0(), "rule__Page__Group_1_0__0");
					put(grammarAccess.getPageAccess().getGroup_1_1(), "rule__Page__Group_1_1__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getQuestionAccess().getGroup(), "rule__Question__Group__0");
					put(grammarAccess.getQuestionAccess().getGroup_1_1(), "rule__Question__Group_1_1__0");
					put(grammarAccess.getQuestionAccess().getGroup_1_2(), "rule__Question__Group_1_2__0");
					put(grammarAccess.getQuestionAccess().getGroup_1_3(), "rule__Question__Group_1_3__0");
					put(grammarAccess.getQuestionAccess().getGroup_1_4(), "rule__Question__Group_1_4__0");
					put(grammarAccess.getQuestionAccess().getGroup_1_5(), "rule__Question__Group_1_5__0");
					put(grammarAccess.getQuestionAccess().getGroup_1_6(), "rule__Question__Group_1_6__0");
					put(grammarAccess.getQuestionAccess().getGroup_1_7(), "rule__Question__Group_1_7__0");
					put(grammarAccess.getQuestionAccess().getGroup_1_8(), "rule__Question__Group_1_8__0");
					put(grammarAccess.getQuestionAccess().getGroup_1_8_2(), "rule__Question__Group_1_8_2__0");
					put(grammarAccess.getQuestionAccess().getGroup_1_9(), "rule__Question__Group_1_9__0");
					put(grammarAccess.getQuestionAccess().getGroup_1_10(), "rule__Question__Group_1_10__0");
					put(grammarAccess.getQuestionAccess().getGroup_1_11(), "rule__Question__Group_1_11__0");
					put(grammarAccess.getQuestionAccess().getGroup_1_12(), "rule__Question__Group_1_12__0");
					put(grammarAccess.getQuestionAccess().getGroup_1_13(), "rule__Question__Group_1_13__0");
					put(grammarAccess.getQuestionAccess().getGroup_2_0(), "rule__Question__Group_2_0__0");
					put(grammarAccess.getQuestionAccess().getGroup_2_0_2(), "rule__Question__Group_2_0_2__0");
					put(grammarAccess.getQuestionAccess().getGroup_2_1(), "rule__Question__Group_2_1__0");
					put(grammarAccess.getQuestionAccess().getGroup_2_2(), "rule__Question__Group_2_2__0");
					put(grammarAccess.getQuestionAccess().getGroup_2_2_2(), "rule__Question__Group_2_2_2__0");
					put(grammarAccess.getTextValueAccess().getGroup(), "rule__TextValue__Group__0");
					put(grammarAccess.getTextValueAccess().getGroup_3(), "rule__TextValue__Group_3__0");
					put(grammarAccess.getMultiTextItemAccess().getGroup(), "rule__MultiTextItem__Group__0");
					put(grammarAccess.getSurveyAccess().getHideNavigationButtonsAssignment_0_0(), "rule__Survey__HideNavigationButtonsAssignment_0_0");
					put(grammarAccess.getSurveyAccess().getHidePageTitlesAssignment_0_1(), "rule__Survey__HidePageTitlesAssignment_0_1");
					put(grammarAccess.getSurveyAccess().getHideQuestionNumbersAssignment_0_2(), "rule__Survey__HideQuestionNumbersAssignment_0_2");
					put(grammarAccess.getSurveyAccess().getHidePageNumbersAssignment_0_3(), "rule__Survey__HidePageNumbersAssignment_0_3");
					put(grammarAccess.getSurveyAccess().getAuthorAssignment_0_4_1(), "rule__Survey__AuthorAssignment_0_4_1");
					put(grammarAccess.getSurveyAccess().getAuthorAssignment_0_4_2_1(), "rule__Survey__AuthorAssignment_0_4_2_1");
					put(grammarAccess.getSurveyAccess().getTitleAssignment_0_5_1(), "rule__Survey__TitleAssignment_0_5_1");
					put(grammarAccess.getSurveyAccess().getTimeLimitAssignment_0_6_1(), "rule__Survey__TimeLimitAssignment_0_6_1");
					put(grammarAccess.getSurveyAccess().getCompletedMessageAssignment_0_7_1(), "rule__Survey__CompletedMessageAssignment_0_7_1");
					put(grammarAccess.getSurveyAccess().getPageNextTextAssignment_0_8_1(), "rule__Survey__PageNextTextAssignment_0_8_1");
					put(grammarAccess.getSurveyAccess().getPagePrevTextAssignment_0_9_1(), "rule__Survey__PagePrevTextAssignment_0_9_1");
					put(grammarAccess.getSurveyAccess().getCompleteTextAssignment_0_10_1(), "rule__Survey__CompleteTextAssignment_0_10_1");
					put(grammarAccess.getSurveyAccess().getQuestionTitleLocationAssignment_0_11_1(), "rule__Survey__QuestionTitleLocationAssignment_0_11_1");
					put(grammarAccess.getSurveyAccess().getShowProgressBarAssignment_0_12_1(), "rule__Survey__ShowProgressBarAssignment_0_12_1");
					put(grammarAccess.getSurveyAccess().getPagesAssignment_1(), "rule__Survey__PagesAssignment_1");
					put(grammarAccess.getSurveyAccess().getPagesAssignment_2(), "rule__Survey__PagesAssignment_2");
					put(grammarAccess.getPageAccess().getTitleAssignment_1_0_1(), "rule__Page__TitleAssignment_1_0_1");
					put(grammarAccess.getPageAccess().getVisibleIfAssignment_1_1_1(), "rule__Page__VisibleIfAssignment_1_1_1");
					put(grammarAccess.getPageAccess().getQuestionsAssignment_2(), "rule__Page__QuestionsAssignment_2");
					put(grammarAccess.getPageAccess().getQuestionsAssignment_3(), "rule__Page__QuestionsAssignment_3");
					put(grammarAccess.getQuestionAccess().getIsRequiredAssignment_1_0(), "rule__Question__IsRequiredAssignment_1_0");
					put(grammarAccess.getQuestionAccess().getTypeAssignment_1_1_1(), "rule__Question__TypeAssignment_1_1_1");
					put(grammarAccess.getQuestionAccess().getTitleAssignment_1_2_1(), "rule__Question__TitleAssignment_1_2_1");
					put(grammarAccess.getQuestionAccess().getRangeStartAssignment_1_3_1(), "rule__Question__RangeStartAssignment_1_3_1");
					put(grammarAccess.getQuestionAccess().getRangeEndAssignment_1_4_1(), "rule__Question__RangeEndAssignment_1_4_1");
					put(grammarAccess.getQuestionAccess().getInputTypeAssignment_1_5_1(), "rule__Question__InputTypeAssignment_1_5_1");
					put(grammarAccess.getQuestionAccess().getVisibleIfAssignment_1_6_1(), "rule__Question__VisibleIfAssignment_1_6_1");
					put(grammarAccess.getQuestionAccess().getPlaceholderAssignment_1_7_1(), "rule__Question__PlaceholderAssignment_1_7_1");
					put(grammarAccess.getQuestionAccess().getChoicesAssignment_1_8_1(), "rule__Question__ChoicesAssignment_1_8_1");
					put(grammarAccess.getQuestionAccess().getChoicesAssignment_1_8_2_1(), "rule__Question__ChoicesAssignment_1_8_2_1");
					put(grammarAccess.getQuestionAccess().getColCountAssignment_1_9_1(), "rule__Question__ColCountAssignment_1_9_1");
					put(grammarAccess.getQuestionAccess().getQuestionNameAssignment_1_10_1(), "rule__Question__QuestionNameAssignment_1_10_1");
					put(grammarAccess.getQuestionAccess().getRowsAssignment_1_11_1(), "rule__Question__RowsAssignment_1_11_1");
					put(grammarAccess.getQuestionAccess().getMininumRateDescriptionAssignment_1_12_1(), "rule__Question__MininumRateDescriptionAssignment_1_12_1");
					put(grammarAccess.getQuestionAccess().getMaximumRateDescriptionAssignment_1_13_1(), "rule__Question__MaximumRateDescriptionAssignment_1_13_1");
					put(grammarAccess.getQuestionAccess().getMatrixRowsAssignment_2_0_1(), "rule__Question__MatrixRowsAssignment_2_0_1");
					put(grammarAccess.getQuestionAccess().getMatrixRowsAssignment_2_0_2_1(), "rule__Question__MatrixRowsAssignment_2_0_2_1");
					put(grammarAccess.getQuestionAccess().getMultiTextItemsAssignment_2_1_1(), "rule__Question__MultiTextItemsAssignment_2_1_1");
					put(grammarAccess.getQuestionAccess().getMultiTextItemsAssignment_2_1_2(), "rule__Question__MultiTextItemsAssignment_2_1_2");
					put(grammarAccess.getQuestionAccess().getMatrixColumnsAssignment_2_2_1(), "rule__Question__MatrixColumnsAssignment_2_2_1");
					put(grammarAccess.getQuestionAccess().getMatrixColumnsAssignment_2_2_2_1(), "rule__Question__MatrixColumnsAssignment_2_2_2_1");
					put(grammarAccess.getTextValueAccess().getTextAssignment_2(), "rule__TextValue__TextAssignment_2");
					put(grammarAccess.getTextValueAccess().getValueAssignment_3_1(), "rule__TextValue__ValueAssignment_3_1");
					put(grammarAccess.getMultiTextItemAccess().getTitleAssignment_1(), "rule__MultiTextItem__TitleAssignment_1");
					put(grammarAccess.getSurveyAccess().getUnorderedGroup_0(), "rule__Survey__UnorderedGroup_0");
					put(grammarAccess.getPageAccess().getUnorderedGroup_1(), "rule__Page__UnorderedGroup_1");
					put(grammarAccess.getQuestionAccess().getUnorderedGroup_1(), "rule__Question__UnorderedGroup_1");
					put(grammarAccess.getQuestionAccess().getUnorderedGroup_2(), "rule__Question__UnorderedGroup_2");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			xtext.ui.contentassist.antlr.internal.InternalQueryITParser typedParser = (xtext.ui.contentassist.antlr.internal.InternalQueryITParser) parser;
			typedParser.entryRuleSurvey();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public QueryITGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(QueryITGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
