/*
* generated by Xtext
*/
package xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import xtext.services.QueryITGrammarAccess;

public class QueryITParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private QueryITGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected xtext.parser.antlr.internal.InternalQueryITParser createParser(XtextTokenStream stream) {
		return new xtext.parser.antlr.internal.InternalQueryITParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Survey";
	}
	
	public QueryITGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(QueryITGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
